AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ImageAnalysis:
    Properties:
      CodeUri: s3://stine-lambda-staging/757b4ed8565563579396c0a1002be447
      Handler: index.handler
      MemorySize: 256
      Policies:
      - AmazonRekognitionFullAccess
      - CloudWatchLogsFullAccess
      Runtime: nodejs6.10
      Timeout: 30
    Type: AWS::Serverless::Function
  ImageApi:
    Properties:
      CodeUri: s3://stine-lambda-staging/903480d089cec66ae33055051f6b10f7
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ImageDb
      Events:
        GetImage:
          Properties:
            Method: get
            Path: /images/{id}
          Type: Api
        ListAll:
          Properties:
            Method: get
            Path: /images
          Type: Api
      Handler: index.handler
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      - CloudWatchLogsFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  ImageDb:
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
    Type: AWS::Serverless::SimpleTable
  ImageDbUpdate:
    Properties:
      CodeUri: s3://stine-lambda-staging/027205d99bc960ea9ec6aba1ce69d383
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ImageDb
      Handler: index.handler
      Policies:
      - AmazonDynamoDBFullAccess
      - CloudWatchLogsFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  ImagePipelineTrigger:
    Properties:
      CodeUri: s3://stine-lambda-staging/ff02cee21381324567bd1c4405dfc397
      Environment:
        Variables:
          STATE_MACHINE_ARN: arn:aws:states:us-east-1:562907585144:stateMachine:image-pipeline-3
      Events:
        NewImage:
          Properties:
            Bucket:
              Ref: StineLambdaImages
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: index.handler
      Policies:
      - AWSStepFunctionsFullAccess
      - CloudWatchLogsFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  ImageResize:
    Properties:
      CodeUri: s3://stine-lambda-staging/d9bfc5ac033eae03478e9084814941bd
      Environment:
        Variables:
          THUMBNAIL_BUCKET:
            Ref: StineLambdaThumbnails
      Handler: index.handler
      MemorySize: 256
      Policies:
      - AmazonS3FullAccess
      - CloudWatchLogsFullAccess
      Runtime: nodejs6.10
      Timeout: 30
    Type: AWS::Serverless::Function
  StineLambdaImages:
    Type: AWS::S3::Bucket
  StineLambdaThumbnails:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
